/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package eu.tobse.tool.pdfwatermark;

import com.lowagie.text.DocumentException;

import java.io.File;
import java.io.IOException;

public class App {
    /**
     * @param args First argument can be the Path to the PDF file
     */
    public static void main(String[] args) throws IOException, DocumentException {
        if (args.length >= 1) {
            new Watermark(new File(args[0]));
        } else {
            new Watermark();
        }
    }
}
